### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by dmikushin** [edoardoCB/gpu_spmv#1]
Hi @edoardoCB , thank you for working on this project! Could you please help me to sort out the following questions:

1. You mentioned that `The AXT format's software is part of the AXT SPL library registered under a GPL license.` Could you please clarify which flavor of GPL license in this project covered by, specifically? For example, there is GPLv2, LGPL, AGPL and so on. 
2. You mentioned that `The Universidad de Santiago de Compostela partially owns the intellectual rights`. Could you please clarify which license the The Universidad de Santiago is a copyright holder of? Is it the same GPL license to be clarified in point 1, or some other type of license?

**Comment by edoardoCB** [comment]
Hi Dmitry,

 1. License GPL3
 2. I just sent an email asking for this information, because the documents I have do not specify this.

Best regards,
Edoardo

________________________________
De: Dmitry Mikushin ***@***.***>
Enviado: domingo, 10 de abril de 2022 03:49 p. m.
Para: edoardoCB/gpu_spmv ***@***.***>
CC: Edoardo Coronado ***@***.***>; Mention ***@***.***>
Asunto: [edoardoCB/gpu_spmv] Licensing questions (Issue #1)


Hi @edoardoCB<https://github.com/edoardoCB> , thank you for working on this project! Could you please help me to sort out the following questions:

  1.  You mentioned that The AXT format's software is part of the AXT SPL library registered under a GPL license. Could you please clarify which flavor of GPL license in this project covered by, specifically? For example, there is GPLv2, LGPL, AGPL and so on.
  2.  You mentioned that The Universidad de Santiago de Compostela partially owns the intellectual rights. Could you please clarify which license the The Universidad de Santiago is a copyright holder of? Is it the same GPL license to be clarified in point 1, or some other type of license?

**Comment by dmikushin** [comment]
Dear @edoardoCB , how are you?

Do you have any further update about the license?

**Comment by edoardoCB** [comment]
Hi Dmitry,

   It seems the license procedure got to stand still. The last communication I have from the University is from May 10th 2022. Because I've been working in other area and some personal circumstances I have not insisted on the issue.

   I am going to write to the University to ask them and if they are not interested in pursing the license I may be inclined to do it myself.

   In the meantime you can use the code and test it if you are interested. Not sure how long is going to take to solve the license issue, so if you have a application case go ahead!!!

Kind regards,
Edoardo

**Comment by edoardoCB** [comment]
> Dear @edoardoCB , how are you?
> 
> Do you have any further update about the license?

Hi Dmitry,

    According to a University representative the code is under GPL license any use, but commercial is allowed.

Best,
Edoardo

**Comment by dmikushin** [comment]
Hi @edoardoCB ,

> According to a University representative the code is under GPL license any use, but commercial is allowed.

GPL allows commercial use. Do you mean that commercial use is also governed by GPL?

**Comment by edoardoCB** [comment]
Yes, it is as you say. I found this (https://opensource.stackexchange.com/questions/1399/can-gpl-licenced-software-be-used-in-corporate-environments):

_Software licensed with any GNU license can be used and even modified everywhere, including in a corporate environment, without any restrictions.

However be aware that if you (or the company) ever make changes to the software and want to distribute it, it must be distributed with full source code, on the same license terms as the original software.

Also if you make changes to the software and it is licensed using Affero license (eg. AGPL 3.0), and your company is providing web access to this software, then you'll also be required to publish full source code (including your changes)._

**Comment by dmikushin** [comment]
This is clear now, thank you very much!
